---
version: "3.8"

services:
  helloworld-function:
    image: quay.io/rocats/helloworld-function:latest
    container_name: helloworld-function 
    build:
      context: .
      args:
        PYTHON_VERSION: 3.12
    ports:
      - 8080:8080
    restart: unless-stopped
